### ISSUE TITLE
Image Center for typography.css

### ISSUE THREAD

**Issue by UndefinedOffset** [UndefinedOffset/eclipse-silverstripedt#30]
Should add a image centering style to typography.css:

``` css
.typography img.center {
    display: block;

    margin: 0 auto;
}
```
