### ISSUE TITLE
Config YAML template adjustments

### ISSUE THREAD

**Issue by UndefinedOffset** [UndefinedOffset/eclipse-silverstripedt#37]
We should change the template for config.yml to match the silverstripe installer's

Current:
```yml
---
Name: mysite
After:"framework/*", "cms/*"
---
```

Updated:
```yml
---
Name: mysite
After:
    - "framework/*"
    - "cms/*"
---
```
