### ISSUE TITLE
Improved Media Layout Styles

### ISSUE THREAD

**Issue by UndefinedOffset** [UndefinedOffset/eclipse-silverstripedt#49]
We should improve the default theme styles to include media as well as support for the captioned images

```css
.typography img.center, .typography .captionImage.center, .typography .media.center {
    display: block;
    
    margin: 20px auto;
}

.typography img.left, .typography .captionImage.left, .typography .media.left {
    float: left;
    
    margin: 0 20px 20px 0;
}

.typography img.right, .typography .captionImage.right, .typography .media.right {
    float: right;
    
    margin: 0 0 20px 20px;
}

.typography .captionImage img {
    float: none !important;
    
    margin: 0 !important;
}
```
